/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BTCVaultService__factory } from "./BTCVaultService__factory";
export { BTCVaultServiceEn__factory } from "./BTCVaultServiceEn__factory";
