/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BTCVaultService } from "./BTCVaultService";
export type { BTCVaultServiceEn } from "./BTCVaultServiceEn";
